### ISSUE TITLE
Authenticator

### ISSUE THREAD

**Issue by BranicYeti** [Zyncco/Android-App#12]
I just tested, and Zync will hear clipboard updates for apps such as Authenticator. Probably LastPass too. Should we perhaps find a way to optionally blacklist apps like that? We never see that information, and if encryption is enabled, its secure, but people might not be comfortable with this (unintentional) feature. Personally, I think it's a good idea. Copy Authenticator code on my phone and paste it on Site X without any middle steps is amazing, but is that undermining multi-factor authentication?

**Comment by mkotb** [comment]
I have looked into this, and I can't seem to find a way to figure out who wrote the data to the clipboard as when writing, it isn't required to specify the Context (see [here](https://github.com/Zyncco/Android-App/blob/master/app/src/main/java/co/zync/zync/ZyncClipboardService.java#L73-L77)). Due to that fact, I'm unsure if it's possible to blacklist apps which are of the Password/2FA nature

**Comment by aaomidi** [comment]
I think this is perfectly fine. This is why we're using End to End encryption. As long as big enough warnings are displayed its not longer our responsibility. 

Maybe make them type it out `I am willingly putting my device at risk by disabling end to encryption`. Or honestly, it might just be better to not give them that option.

Let me know what you think?

**Comment by BranicYeti** [comment]
I agree, the latter is better, but it's not very user-friendly. Textbox-based confirmation is something Mazen will have to weigh in on in terms of possibility, but I feel like it's a good idea

**Comment by aaomidi** [comment]
This is something that should be brought up on our next meeting.

Lets discuss it there and on slack.

**Comment by aaomidi** [comment]
[Telegram poll link](https://t.me/Zyncco/8)

**Comment by mkotb** [comment]
Encryption is enforced and you can now toggle the app from listening to your keyboard by clicking the logo on the main menu. Issue resolved.
