### ISSUE TITLE
Feedback page?

### ISSUE THREAD

**Issue by aaomidi** [Zyncco/Android-App#13]
It'd be really nice if we could have a feedback page inside the app.

**Comment by mkotb** [comment]
Where would the feedback go to?

**Comment by aaomidi** [comment]
Us :P We'd just need the server to support it.

**Comment by mkotb** [comment]
Does Firebase have anything that could make implementing this easier for us?

**Comment by aaomidi** [comment]
We could use the messaging system.

**Comment by mkotb** [comment]
Feedback is added. Works by email and no work on @Vilsol's side needs to be done.
