### ISSUE TITLE
Authentication model

### ISSUE THREAD

**Issue by aaomidi** [Zyncco/Android-App#14]
Authentication model should follow the example on https://firebase.google.com/docs/auth/admin/verify-id-tokens

**Comment by mkotb** [comment]
Fixed/Added in [this](https://github.com/Zyncco/Android-App/commit/1e70649d75f611cb30fcd7e5dd702ca8b2565a35#diff-0ba0a874a6cdf9ba3db3f3eea1021301R107) commit
