### ISSUE TITLE
Idea for App Intro

### ISSUE THREAD

**Issue by BranicYeti** [Zyncco/Android-App#3]
# First time opening the app, or if GBoard isn't set up as a keyboard
---
![image](https://cloud.githubusercontent.com/assets/1971818/23869385/ab38f30e-081a-11e7-869b-d4eb53112c06.png)
---
![image](https://cloud.githubusercontent.com/assets/1971818/23869402/b655cf14-081a-11e7-9631-edb8085d5f94.png)
---
![image](https://cloud.githubusercontent.com/assets/1971818/23869426/ca0746aa-081a-11e7-8fcf-2437b0ee5c24.png)
---
![image](https://cloud.githubusercontent.com/assets/1971818/23869430/cfc06cb6-081a-11e7-9d74-ccfea7223b45.png)
---
# After setting GBoard as a keyboard
---
![image](https://cloud.githubusercontent.com/assets/1971818/23869436/d7024c74-081a-11e7-8b31-d34ba2dbfa7e.png)
---
![image](https://cloud.githubusercontent.com/assets/1971818/23869449/dc878092-081a-11e7-8ae1-f38db910dab4.png)
---
# Every subsequent app open
---
![image](https://cloud.githubusercontent.com/assets/1971818/23869458/e1d51b68-081a-11e7-8e25-04409b3ef187.png)

**Comment by BranicYeti** [comment]
Pictures are rather large, probably partly because they're screenshots from an iPad.

**Comment by aaomidi** [comment]
Thanks!
